/** This comment is generated by system, put your components description on this section
    DO NOT CHANGE THIS COMMENT OPENING/CLOSING CHARACTERS OR YOUR COMPONENT
    DESCRIPTION WILL BE IGNORED, PUT YOUR DESCRIPTION AFTER 4 DASHES BELOW
----
Shows the customer's current status (Open, Verified, Diterima, or Ditolak) as a colored badge, used in tables or details.  
Props:
```tsx
type CustomerStatusBadgeProps = {
  status: "Open" | "Verified" | "Diterima" | "Ditolak";
  className?: string;
};
```
**/
import { Badge } from "@/components/ui/badge";

type CustomerStatusBadgeProps = {
  status: "Open" | "Verified" | "Diterima" | "Ditolak";
  className?: string;
};

export function CustomerStatusBadge({ status, className }: CustomerStatusBadgeProps) {
  const getStatusVariant = () => {
    switch (status) {
      case "Open":
        return "secondary";
      case "Verified":
        return "default";
      case "Diterima":
        return "outline";
      case "Ditolak":
        return "destructive";
      default:
        return "secondary";
    }
  };

  return (
    <Badge variant={getStatusVariant()} className={className}>
      {status}
    </Badge>
  );
}
