/** This comment is generated by system, put your components description on this section
    DO NOT CHANGE THIS COMMENT OPENING/CLOSING CHARACTERS OR YOUR COMPONENT
    DESCRIPTION WILL BE IGNORED, PUT YOUR DESCRIPTION AFTER 4 DASHES BELOW
----
Action buttons (Edit, Verify, Accept, Reject, Details etc.) for each row in customer table, rendered based on status and with customizable actions.  
Props:
```tsx
type DataTableActionsProps = {
  status: "Open" | "Verified" | "Diterima" | "Ditolak";
  canEdit?: boolean;
  canVerify?: boolean;
  canSetFinalStatus?: boolean;
  onEdit?: () => void;
  onVerify?: () => void;
  onAccept?: () => void;
  onReject?: () => void;
  onDetail?: () => void;
};
```
**/
import { Button } from "@/components/ui/button"
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu"
import { MoreHorizontal } from "lucide-react"

type DataTableActionsProps = {
  status: "Open" | "Verified" | "Diterima" | "Ditolak"
  canEdit?: boolean
  canVerify?: boolean
  canSetFinalStatus?: boolean
  onEdit?: () => void
  onVerify?: () => void
  onAccept?: () => void
  onReject?: () => void
  onDetail?: () => void
}

export function DataTableActions({
  status,
  canEdit = true,
  canVerify = true,
  canSetFinalStatus = true,
  onEdit,
  onVerify,
  onAccept,
  onReject,
  onDetail,
}: DataTableActionsProps) {
  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="ghost" className="h-8 w-8 p-0">
          <span className="sr-only">Open menu</span>
          <MoreHorizontal className="h-4 w-4" />
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end">
        <DropdownMenuItem onSelect={onDetail}>Detail</DropdownMenuItem>
        {canEdit && status !== "Ditolak" && (
          <DropdownMenuItem onSelect={onEdit}>Edit</DropdownMenuItem>
        )}
        {canVerify && status === "Open" && (
          <DropdownMenuItem onSelect={onVerify}>Verifikasi</DropdownMenuItem>
        )}
        {canSetFinalStatus && status === "Verified" && (
          <>
            <DropdownMenuItem onSelect={onAccept}>Terima</DropdownMenuItem>
            <DropdownMenuItem onSelect={onReject}>Tolak</DropdownMenuItem>
          </>
        )}
      </DropdownMenuContent>
    </DropdownMenu>
  )
}
