/** This comment is generated by system, put your components description on this section
    DO NOT CHANGE THIS COMMENT OPENING/CLOSING CHARACTERS OR YOUR COMPONENT
    DESCRIPTION WILL BE IGNORED, PUT YOUR DESCRIPTION AFTER 4 DASHES BELOW
----
Displays page title with optional breadcrumb navigation and description.  
Props:
```tsx
type PageTitleProps = {
  title: string;
  description?: string;
  breadcrumbs?: { label: string; href?: string }[];
};
```
**/
import { Breadcrumb, BreadcrumbItem, BreadcrumbLink, BreadcrumbList, BreadcrumbPage, BreadcrumbSeparator } from "@/components/ui/breadcrumb";

type PageTitleProps = {
  title: string;
  description?: string;
  breadcrumbs?: { label: string; href?: string }[];
};

export function PageTitle({ title, description, breadcrumbs }: PageTitleProps) {
  return (
    <div className="space-y-2">
      {breadcrumbs && breadcrumbs.length > 0 && (
        <Breadcrumb>
          <BreadcrumbList>
            {breadcrumbs.map((crumb, index) => (
              <div key={index} className="flex items-center gap-2">
                <BreadcrumbItem>
                  {crumb.href ? (
                    <BreadcrumbLink href={crumb.href}>{crumb.label}</BreadcrumbLink>
                  ) : (
                    <BreadcrumbPage>{crumb.label}</BreadcrumbPage>
                  )}
                </BreadcrumbItem>
                {index < breadcrumbs.length - 1 && (
                  <BreadcrumbSeparator />
                )}
              </div>
            ))}
          </BreadcrumbList>
        </Breadcrumb>
      )}
      <h1 className="text-2xl font-bold tracking-tight">{title}</h1>
      {description && <p className="text-muted-foreground">{description}</p>}
    </div>
  );
}
