/** This comment is generated by system, put your components description on this section
    DO NOT CHANGE THIS COMMENT OPENING/CLOSING CHARACTERS OR YOUR COMPONENT
    DESCRIPTION WILL BE IGNORED, PUT YOUR DESCRIPTION AFTER 4 DASHES BELOW
----
Card component for showing summary stats on the dashboard (e.g. total Open/Verified/Diterima/Ditolak) with optional icon and custom color.  
Props:
```tsx
type StatsCardProps = {
  title: string;
  value: string | number;
  icon?: React.ReactNode;
  color?: string;
  className?: string;
};
```
**/
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card"

type StatsCardProps = {
  title: string;
  value: string | number;
  icon?: React.ReactNode;
  color?: string;
  className?: string;
};

function StatsCard({ title, value, icon, color, className }: StatsCardProps) {
  return (
    <Card className={className}>
      <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
        <CardTitle className="text-sm font-medium">{title}</CardTitle>
        {icon && <div className={`text-${color || 'primary'}`}>{icon}</div>}
      </CardHeader>
      <CardContent>
        <div className={`text-2xl font-bold text-${color || 'primary'}`}>
          {value}
        </div>
      </CardContent>
    </Card>
  )
}

export { StatsCard }
