/** This comment is generated by system, put your components description on this section
    DO NOT CHANGE THIS COMMENT OPENING/CLOSING CHARACTERS OR YOUR COMPONENT
    DESCRIPTION WILL BE IGNORED, PUT YOUR DESCRIPTION AFTER 4 DASHES BELOW
----
User avatar/profile dropdown menu with optional display of name, email and entries for "Profile" and "Logout".  
Props:
```tsx
type UserAvatarMenuProps = {
  name?: string;
  email?: string;
  onLogout?: () => void;
  showProfileLink?: boolean;
};
```
**/
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar";
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator } from "@/components/ui/dropdown-menu";
import { LogOut, User } from "lucide-react";

type UserAvatarMenuProps = {
  name?: string;
  email?: string;
  onLogout?: () => void;
  showProfileLink?: boolean;
};

export function UserAvatarMenu({ name, email, onLogout, showProfileLink = true }: UserAvatarMenuProps) {
  const initials = name
    ? name.split(' ').map(n => n[0]).join('').substring(0, 2).toUpperCase()
    : 'U';

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Avatar className="cursor-pointer">
          <AvatarImage src={`https://api.dicebear.com/7.x/initials/svg?seed=${name || 'user'}`} alt={name || 'User avatar'} />
          <AvatarFallback>{initials}</AvatarFallback>
        </Avatar>
      </DropdownMenuTrigger>
      <DropdownMenuContent className="w-56" align="end">
        <div className="px-2 py-1.5">
          {name && <p className="font-medium truncate">{name}</p>}
          {email && <p className="text-sm text-muted-foreground truncate">{email}</p>}
        </div>
        <DropdownMenuSeparator />
        {showProfileLink && (
          <DropdownMenuItem>
            <User className="mr-2 h-4 w-4" />
            <span>Profile</span>
          </DropdownMenuItem>
        )}
        <DropdownMenuSeparator />
        <DropdownMenuItem onSelect={onLogout}>
          <LogOut className="mr-2 h-4 w-4" />
          <span>Log out</span>
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
}
